import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: 'Helvetica', color: '#0f172a' },
  header: { marginBottom: 18, borderBottomWidth: 1, borderColor: '#e2e8f0', paddingBottom: 10 },
  brand: { fontSize: 10, color: '#64748b', marginBottom: 4 },
  title: { fontSize: 18, fontWeight: 700 },
  subtitle: { fontSize: 10, color: '#475569', marginTop: 2 },
  scope: { marginTop: 10, fontSize: 9, color: '#334155' },
  badge: {
    marginTop: 10, alignSelf: 'flex-start', paddingHorizontal: 6, paddingVertical: 2,
    borderRadius: 3, fontSize: 8,
  },
  badgeOk: { backgroundColor: '#ecfdf5', color: '#047857' },
  badgeBad: { backgroundColor: '#fef2f2', color: '#b91c1c' },
  entry: {
    marginBottom: 10, padding: 8, borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 4,
  },
  entryHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  type: { fontSize: 8, color: '#0f172a', fontWeight: 700, textTransform: 'uppercase' },
  time: { fontSize: 8, color: '#64748b' },
  content: { fontSize: 10, color: '#1e293b', marginVertical: 4 },
  hashRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 },
  hashLabel: { fontSize: 7, color: '#94a3b8', textTransform: 'uppercase' },
  hashValue: { fontSize: 8, fontFamily: 'Courier', color: '#475569' },
  footer: {
    position: 'absolute', bottom: 24, left: 36, right: 36,
    fontSize: 8, color: '#94a3b8', textAlign: 'center',
  },
});

function shortHash(hex) {
  if (!hex) return '—';
  if (hex === 'GENESIS') return 'GENESIS';
  return `${hex.slice(0, 12)}…${hex.slice(-6)}`;
}

function formatTime(ts) {
  const date = ts?.toDate?.();
  if (!date) return '—';
  return date.toLocaleString();
}

export default function ReceiptPDF({ project, entries, chainValid }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>RECEIPT — Tamper-evident proof of work</Text>
          <Text style={styles.title}>{project.name}</Text>
          <Text style={styles.subtitle}>
            Client: {project.client_name}
            {project.rate ? `  ·  Rate: ₹${project.rate}` : ''}
          </Text>
          {project.scope ? <Text style={styles.scope}>{project.scope}</Text> : null}
          <Text
            style={[styles.badge, chainValid ? styles.badgeOk : styles.badgeBad]}
          >
            {chainValid ? 'Chain intact' : 'Chain BROKEN — verify in app'}
          </Text>
        </View>

        {entries.map((entry, index) => (
          <View key={entry.id} style={styles.entry} wrap={false}>
            <View style={styles.entryHeader}>
              <Text style={styles.type}>
                #{index + 1} · {entry.type}
              </Text>
              <Text style={styles.time}>{formatTime(entry.created_at)}</Text>
            </View>
            <Text style={styles.content}>{entry.content}</Text>
            {entry.file_url ? (
              <Text style={[styles.content, { color: '#0369a1' }]}>
                Link: {entry.file_url}
              </Text>
            ) : null}
            <View style={styles.hashRow}>
              <View>
                <Text style={styles.hashLabel}>prev</Text>
                <Text style={styles.hashValue}>{shortHash(entry.prev_hash)}</Text>
              </View>
              <View>
                <Text style={styles.hashLabel}>self</Text>
                <Text style={styles.hashValue}>{shortHash(entry.self_hash)}</Text>
              </View>
            </View>
          </View>
        ))}

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Generated by Receipt · ${pageNumber} / ${totalPages} · Verify chain integrity at the live timeline.`
          }
          fixed
        />
      </Page>
    </Document>
  );
}
